# Generated by Django 2.1.1 on 2018-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('first_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('is_staff', models.BooleanField(default=True, verbose_name='是否在职')),
            ],
        ),
    ]
